### ISSUE TITLE
Curious error when using `session.get(url, allow_redirects=False)`

### ISSUE THREAD

**Issue by peterbe** [loads/molotov#62]
My service is all about returning 302 responses. The `Location` header it returns is a public S3 URL. I'm only interested in "how fast" I can yield these 302 response. I'm not interested in (molotov) downloading the content when following the 302s. 

[Here's my loadtest.py](https://github.com/mozilla-services/tecken-loadtests/blob/b9addecb049c0a8712697b3d6fda6e0489768d8b/loadtest.py#L119)
When I replace `session.get(url)` with `session.get(url, allow_redirects=False)` it barfs this error:

```
▶ URL_SERVER=https://symbols.stage.mozaws.net molotov --max-runs 10 -cx -vv loadtest.py
**** Molotov v1.2. Happy breaking! ****
[55645] Preparing 1 workers...OK
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

GET https://symbols.stage.mozaws.net/XUL/378A8EDDE8123A19BA874E9F5C73E4A50/XUL.sym
Accept-Encoding: gzip, deflate
Accept: */*
Host: symbols.stage.mozaws.net
User-Agent: Python/3.5 aiohttp/2.0.7
Content-Length: 0
SUCCESSES: 0 | FAILURES: 0
=============================================

AttributeError("'EmptyStreamReader' object has no attribute 'unread_data'",)
  File "/Users/peterbe/virtualenvs/tecken-loadtests/lib/python3.5/site-packages/molotov/fmwk.py", line 73, in step
    await func(session, *args_, **kw)
  File "loadtest.py", line 119, in scenario_download
    async with session.get(url, allow_redirects=False) as resp:
  File "/Users/peterbe/virtualenvs/tecken-loadtests/lib/python3.5/site-packages/aiohttp/client.py", line 626, in __aenter__
    self._resp = yield from self._coro
  File "/Users/peterbe/virtualenvs/tecken-loadtests/lib/python3.5/site-packages/molotov/session.py", line 77, in _request
    await self.print_response(resp)
  File "/Users/peterbe/virtualenvs/tecken-loadtests/lib/python3.5/site-packages/molotov/session.py", line 121, in print_response
    resp.content.unread_data(content)
SUCCESSES: 0 | FAILURES: 1
*** Bye ***
```

The reason why I know it's proceeding to actually download, is because when I run with `-vv` I can see the content of some of the symbol files it's only supposed to *ask* if they exist.

**Comment by tarekziade** [comment]
I am not able to reproduce this behavior with Molotov master. I added a test to make sure the redirects works and using allow_redirects=False don't download the content.

Could you try with Molotov master if you are running with the release?

Thanks. If we still have the problem we'll need to investigate with the S3 server and see how it's different from my test server redirect implementation

**Comment by peterbe** [comment]
To reproduce, check out this branch: https://github.com/mozilla-services/tecken-loadtests/compare/mozilla-services:master...peterbe:dont-follow-download-redirects

Here's what I did locally:
```
▶ pip install -I -U git+git://github.com/loads/molotov.git
```
and 
```
▶ URL_SERVER=https://symbols.stage.mozaws.net molotov --max-runs 10 -cx -vv loadtest.py
**** Molotov v1.2. Happy breaking! ****
[97616] Preparing 1 workers...OK
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

GET https://symbols.stage.mozaws.net/xul.pdb/467546A7AE9245C9A9F6D31A4CAC2F542/xul.sym
Accept: */*
Accept-Encoding: gzip, deflate
Host: symbols.stage.mozaws.net
User-Agent: Python/3.5 aiohttp/2.1.0
Content-Length: 0
SUCCESSES: 0 | FAILURES: 0
=============================================

AttributeError("'EmptyStreamReader' object has no attribute 'unread_data'",)
  File "/Users/peterbe/virtualenvs/tecken-loadtests/lib/python3.5/site-packages/molotov/fmwk.py", line 73, in step
    await func(session, *args_, **kw)
  File "loadtest.py", line 119, in scenario_download
    async with session.get(url, allow_redirects=False) as resp:
  File "/Users/peterbe/virtualenvs/tecken-loadtests/lib/python3.5/site-packages/aiohttp/client.py", line 636, in __aenter__
    self._resp = yield from self._coro
  File "/Users/peterbe/virtualenvs/tecken-loadtests/lib/python3.5/site-packages/molotov/session.py", line 77, in _request
    await self.print_response(resp)
  File "/Users/peterbe/virtualenvs/tecken-loadtests/lib/python3.5/site-packages/molotov/session.py", line 121, in print_response
    resp.content.unread_data(content)
SUCCESSES: 0 | FAILURES: 1
*** Bye ***
```

**Comment by tarekziade** [comment]
ok thanks a lot, can you pip freeze in your virtualenv so I double check all the deps versions ? thx

**Comment by tarekziade** [comment]
Crap .... It works for me, but I had to use http:// instead of https:// for the stage server because I get a SSL: CERTIFICATE_VERIFY_FAILED for some reason

**Comment by tarekziade** [comment]
Good news, I can reproduce with 3.5 (works on 3.6)
